[project]
name = "why-turn-on-computer"
version = "0.1.0"
description = ""
authors = [
  { name = "Kolja Sam", email = "github@koljapluemer.com" }
]
requires-python = ">=3.12,<3.15"
dependencies = [
  "pywebview==5.2",
  "appdirs==1.4.4",
  "pyinstaller>=6.15.0,<7.0.0"
]

[tool.uv]
package = false
